# This is ".github/workflows/gh-pages.yml" file.
# This is an EXAMPLE of "GitHub Actions Workflow file".

name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - uses: actions/checkout@v2

      # Install .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.302     

      # Publish the site
      - name: Publish
        run: |
          cp wwwroot/index.html wwwroot/404.html
          dotnet publish MyPortfolio.sln -c:Release -o:publish -p:GHPages=true

      # changes the base-tag in index.html from '/' to 'my-portfolio-blazor' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to my-portfolio-blazor
        run: sed -i 's/<base href="\/" \/>/<base href="\/my-portfolio-blazor\/" \/>/g' publish/wwwroot/index.html    

      # copy index.html to 404.html
      - name: copy index.html to 404.html
        run: cp publish/wwwroot/index.html publish/wwwroot/404.html

      # add .nojekyll file
      - name: Add .nojekyll file
        run: touch publish/wwwroot/.nojekyll
        
      # Deploy the site
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: publish/wwwroot
