name: MyPortfolio

on:
  push:
    branches:
    - master  # default branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0'
    - name: Publish
      run: dotnet publish -c Release -o release
    - name: Set base
      run: sed -i 's/<base href="\/"/<base href="\/MyPortfolio\/"/g' release/wwwroot/index.html >> release/wwwroot/index.html
    - name: No Jekyll
      run: touch release/wwwroot/.nojekyll
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages  # deploying branch
        PUBLISH_DIR: ./release/wwwroot
